# Site Settings
title: Ashwin De Silva
subtitle: "Researcher. Engineer. Instructor"
email: ashwind@uom.lk
description: >
  Researcher. Engineer. Instructor.
baseurl: ""
url: "https://laknath1996.github.io/"
twitter_username: AshwindeSilva1
github_username:  Laknath1996

social-network-links:
  rss: true
  email: "ashwind@uom.lk"
  facebook: laknath.mikoyan
  github: Laknath1996
  twitter: AshwindeSilva1

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
